development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: programmer_development
  pool: 5
  username: root
  password: pass

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: programmer_test
  pool: 5
  username: root
  password: pass

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: programmer_production
  pool: 5
  username: root
  password: pass