# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c80ebe735ba3d4a4ae8abff74b40554b774c3ba7ca48bdb71c54e2fa806080765c9e576a5be3b3071eb0e8126165014515f6f36ca03afdbac0e9b17e9801a7c6

test:
  secret_key_base: fd9e74cc411666b30b19c085f3a25b54a564b8d9b5c9f81c1809c7bad64baf2c3f0f984bf070e27350f566ff68db6d3f987d6c994ca242569bfa3ece47bd6ef6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
